name: petmeter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.11.3  
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
